import "./globals.css";
import Header from "@/components/Header";
import { Archivo } from "next/font/google";
import Footer from "@/components/Footer";
//import Header from "@/components/HeaderServer";

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["300", "400","500"], // pick what you actually use
  style: ["normal","italic"],
  variable: "--font-archivo",     // exposes a CSS var
  display: "swap",
});

export const metadata = { title: "One platform group", description: "Hackathon project" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${archivo.variable}`}>
        <Header /> 
        {children}
        <Footer />
      </body>
    </html>
  );
}

/* export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
} */



/* import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
 */